openapi: 3.0.0
info:
  title: Text Storage API
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: local development server
  - url: https://textdrop.com
    description: main production server
  - url: https://textdrop-staging.com
    description: staging server for testing purposes only

paths:
  /api/text/store:
    post:
      operationId: storeText
      summary: Store text fragment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextFragment'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextFragmentResponse'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /api/text/retrieve:
    get:
      operationId: retrieveText
      summary: Searches the texts by IDS
      parameters:
        - name: text_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextFragmentResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

components:
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnprocessableEntity:
      description: The payload contains invalid values.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://text-storage-dev.auth0.com/.well-known/openid-configuration
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://text-storage-dev.auth0.com/oauth/token
          scopes: {}
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          oneOf:
            - type: string
            - type: array

    TextFragment:
      type: object
      required:
        - text
        - author
      properties:
        text:
          type: string
          description: The text to be stored
        author:
          type: string
          description: The author of the text fragment
        source:
          type: string
          default: "Source not stated"
          description: The source of the text fragment
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the text fragment

    TextFragmentResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the stored text fragment
        text:
          type: string
          description: The stored text fragment
        author:
          type: string
          description: The author of the text fragment
        source:
          type: string
          description: The source of the text fragment
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the text fragment
        created_at:
          type: string
          format: date-time
          description: Timestamp when the text fragment was stored

security:
  - oauth2:
      - storeText
      - retrieveText
  - bearerAuth:
      - storeText
      - retrieveText